modLoader="javafml"
loaderVersion="[60,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues"

[[mods]]
modId="witherstormmod"
version="1.0.0-1.21.10"
displayName="Cracker's Wither Storm Mod"
logoFile="wither_storm_mod_logo.png"
displayURL=""
updateJSONURL=""
credits='''
Antimo & Welles https://linktr.ee/antimowelles
Telltale for the inspiration and sound effects
Jackbot for the 1.21.10 port
Nazaru for additional code and assets
McFella for additional textures
Mar Mar for music https://www.youtube.com/watch?v=qtMPeI1T5iA
'''
authors="nonamecrackers2, Jackbot50"
description='''
Adds the Wither Storm from Minecraft: Story Mode, updated to Minecraft 1.21.10
'''

[[dependencies.witherstormmod]]
    modId="forge"
    mandatory=true
    versionRange="[60,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.witherstormmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.10,1.22)"
    ordering="NONE"
    side="BOTH"

# CrackersLib dependency will be added once we confirm a 1.21.x version exists
